language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - iojs
  - iojs-v1.0.4
script:
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/unittests.js
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/servertests.js
env: IMPRESS_MODE=test
