language: node_js
node_js:
  - 6
  - 8
  - 9
sudo: false
env: IMPRESS_MODE=test
services:
  - mongodb
install:
  - npm install
  - npm install mongodb@2
script:
  - npm run lint
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/unittests.js
  - node --stack-trace-limit=1000 --allow-natives-syntax ./tests/integration.js
